# Veusz build using PyPI packages on Ubuntu

name: Ubuntu build using pip packages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.3'
    - name: Upgrade pip
      run : |
        python -V
        python -m pip install --upgrade pip
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        cache: 'true'
        cache-key-prefix: 'qt-ubuntu-v3'
        version: '6.9.1'
        setup-python: false
    - name: Install Python dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build extensions
      run: |
        python setup.py build_ext --inplace
    - name: Run tests
      run: |
        set -euo pipefail
        unset QT_ROOT_DIR QML2_IMPORT_PATH
        QT_LIBDIR="$(python -c 'from PyQt6.QtCore import QLibraryInfo as Q; print(Q.path(Q.LibraryPath.LibrariesPath))')"
        QT_PLUGINSDIR="$(python -c 'from PyQt6.QtCore import QLibraryInfo as Q; print(Q.path(Q.LibraryPath.PluginsPath))')"
        export LD_LIBRARY_PATH="${QT_LIBDIR}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
        export QT_PLUGIN_PATH="${QT_PLUGINSDIR}"
        export QT_QPA_PLATFORM=minimal
        export VEUSZ_INPLACE_TEST=1
        python tests/runselftest.py
