# Veusz build using distribution packages on Ubuntu

name: Ubuntu build using distribution packages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install qt6-base-dev qt6-base-dev-tools \
          python3-all python3-astropy python3-h5py python3-pyqt6 \
          python3-setuptools python3-all-dev python3-numpy python3-sip-dev \
          pyqt6-dev pyqt6-dev-tools qmake6

    - name: Build extensions
      run: |
        python3 setup.py build_ext --inplace
    - name: Run tests
      run: |
        QT_QPA_PLATFORM=minimal VEUSZ_INPLACE_TEST=1 python3 tests/runselftest.py
