name: Ubuntu build using pip packages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Upgrade pip
      run : |
        python -V
        python -m pip install --upgrade pip
      
    - name: Install system dependencies for Qt6
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential qmake6 \
          libxcb1-dev libx11-dev libxext-dev \
          qt6-base-dev qt6-declarative-dev qt6-webengine-dev
        dpkg -l | grep qt6

    - name: Install Python dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip list

    - name: Build extensions
      run: |
        python setup.py build_ext --inplace
  
    - name: Run tests
      env:
        LD_LIBRARY_PATH: ${{ env.QT_ROOT_DIR }}/lib:${{ env.LD_LIBRARY_PATH }}
        QT_QPA_PLATFORM: minimal
        VEUSZ_INPLACE_TEST: 1
      run: |
        tests/runselftest.py
