# make .whl for Windows

name: Build windows wheels

on:
  #release:
  #  types: [created]
  pull_request:
    branches: [ wheel_productions ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
  
    steps:
    
    - uses: actions/checkout@v2
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache
 
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        modules: 'qtsvg'  
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Dependencies by pip
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U setuptools wheel 
        python -m pip install -r requirements.txt
        
    - name: Build Wheels
      run: |
        python setup.py sdist bdist_wheel       
        
    - name: Upload Wheels
      uses: actions/upload-artifact@v2
      with:
        name: win-wheels
        path: dist\*.whl
